apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
    - name: connectionString # Required when not using Azure Authentication.
      value: "Endpoint=sb://gyrsb2.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=fBj4vAAhqXcLd1qkUBh5SEo4ycjSXmARY+ASbJ4UUms="
scopes:
  - usermanagementservice
  - analysisservice
  - telescopeservice
  # Tobbi service-eket ide tedd be