apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  initTimeout: 5m
  metadata:
  - name: url
    value: https://gyrcosmos.documents.azure.com:443/
  - name: masterKey
    value: FkZVJPbpVGlTPtAJ9rp9SgQOp16Wjfq7jgdd4z9TEhvwdzqgPirBKxxVAc7xOE0HFcOwDpZOrEVeACDbksHk4Q==
  - name: database
    value: poc
  - name: collection
    value: images